[0m[[0m[31merror[0m] [0m[0mC:\Users\viyadav\Desktop\Galactus_Docs\GTV_test\src\main\scala\person_level.scala:300:5: value series_day is not a member of SVE[0m
[0m[[0m[31merror[0m] [0m[0mmsd.series_day()[0m
[0m[[0m[31merror[0m] [0m[0m    ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
